# texto curto explicando o studio
description: Example of stack
# Nome gerado pelo cli em kebab-case
name: example-portal-stack

# Nome com formatação livre que será exibido no portal.
display-name: Example Portal Stack

# caso a picture esteja fora do repo colocar uma url externa
# caso a picture esteja no repo fornecer o path
picture: "https://urbanarts.vteximg.com.br/arquivos/ids/7460265-1000-1000/486933_Ampliada.jpg"

# Especificar a categoria da stack.
# Categorias disponíveis:
# [sre, frontend, backend, fullStack, analytics]
category: backend

# Lista de tecnologias que você gostaria de enfatizar que é compativel
compatibility:
  - spring
  - kotlin

# tecnologies que a stack utiliza
# A lista completa das tecnologias disponiveis que podem ser cadastradas estao disponiveis na Documentacao para consulta
technologies: ["OpenAPI", "SpringBoot"]

# Especificar um arquivo .md que explique em detalhes o objetivo da stack
# por padrão o valor é about.md
about: about.md
# Especificar um arquivo .md com exemplos da utilização da stack.
# por padrão o valor é useCase.md
use-case: useCase.md
